### ISSUE TITLE
PORT issue: always conflict with the app PORT

### ISSUE THREAD

**Issue by sunruoshi** [druv5319/Sneaks-API#10]
## The PORT listening is a MUST-HAVE when require this module? 

It is always conflict with the app PORT when integrate this module to an web application. How to fix it?

**Comment by druv5319** [comment]
If it is being an issue. You can remove it in the index.js file. Let me know if this works.

**Comment by anonyymous1** [comment]
Same issue as above, using is for a school project. When integrating with a web application it conflict with app PORT. I have tried to remove the file and then nothing works. Locally works fine.

**Comment by druv5319** [comment]
Did you remove the whole file or just that line that references the port?

**Comment by sunruoshi** [comment]
> Did you remove the whole file or just that line that references the port?

My solution is deploy the Sneakers-Api separately and fetch the data from url.
