### ISSUE TITLE
imageLinks

### ISSUE THREAD

**Issue by jericoxnavarro** [druv5319/Sneaks-API#11]
Same issue and I think if I GET request an http://localhost:3000/id/${styleID}/prices in like a 20 request that error will occur.
```javascript
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/mnt/d/Project/Hypekicks-web/backend/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1605155076168,
    socket: 1605155076231,
    lookup: 1605155076231,
    connect: 1605155076231,
    secureConnect: 1605155076231,
    upload: 1605155076231,
    response: 1605155076340,
    end: 1605155076342,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 63,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: NaN,
      firstByte: 109,
      download: 2,
      total: 174
    }
  }
}
Error: Could not connect to StockX while searching '
    at Object.getPrices (/mnt/d/Project/Hypekicks-web/backend/scrapers/stockx-scraper.js:93:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Could not connect to Flight Club while searching '555088-105' Error: 
    at Object.getPrices (/mnt/d/Project/Hypekicks-web/backend/scrapers/flightclub-scraper.js:76:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Could not connect to Goat while grabbing pictures for '555088-105' Error: 
    at Object.getPictures (/mnt/d/Project/Hypekicks-web/backend/scrapers/goat-scraper.js:104:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/mnt/d/Project/Hypekicks-web/backend/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1605155077174,
    socket: 1605155077499,
    lookup: 1605155077499,
    connect: 1605155077499,
    secureConnect: 1605155077499,
    upload: 1605155077499,
    response: 1605155077966,
    end: 1605155077967,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 325,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: NaN,
      firstByte: 467,
      download: 1,
      total: 793
    }
  }
}
Error: Could not connect to Goat while searching '555088-105' Error:
    at Object.getPrices (/mnt/d/Project/Hypekicks-web/backend/scrapers/goat-scraper.js:64:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by druv5319** [comment]
Just redownloaded the API and tested it out and works fine. Might be because you've sent too many requests? Does it still work and how often does this show up?

**Comment by jericoxnavarro** [comment]
![vid](https://user-images.githubusercontent.com/38254143/99184438-b706bf00-277d-11eb-8475-be15e2549d7a.gif)
Yup if I sent too many requests the error will show up. But no need for the image I already fix it, instead of the image links in **GOAT**, I manage to get the images in **stockX**. What my concern now is how can I get like a **1000** results or more? Like if I search nike in `/search/:shoe` I want to get a **1000** results. Cuz I want to store it to my DB for me to optimize the response time in my API. BTW thank you for your response.

**Comment by druv5319** [comment]
App looks great! Check out line 19 on the stockx scraper. There is a hits per page parameter where you can change its value. This value is limited so you’re gonna have the change the page number parameter along with it. I’m not sure exactly how to change the page number but I’ll figure out and send it to you later

**Comment by jericoxnavarro** [comment]
Thank you so much😇

**Comment by druv5319** [comment]
Will you be posting the project on GitHub? I’d love to show it off in my sneaks api repository

**Comment by jericoxnavarro** [comment]
Yup after I finish the project but for now, it is on private I will be setting it to the public after the project is done.

**Comment by jericoxnavarro** [comment]
It works thanks.  I change it to 1000 and it responds like 900+ shoes. I have a Question haha, is the **sneaks-api** only get shoes? is there a way that the API will also get streetwears in **stockX**? BTW don't close this issue so that I can notify you if the project is done. Thanks!!

**Comment by druv5319** [comment]
You can get streetwear products by deleting line 29 on the stockX scraper, however its very limited and it'll only show prices and streetwear products from stockX.

**Comment by erikmaday** [comment]
Hey, I've been working on a project with this API and it's great. I too was wondering about the number of results issue, and I was able to modify the search endpoint to accept a results count as a query parameter so that the endpoint would return up to that many results. Wondering if this would be worth a PR, or if it's even functionality you're interested in adding.

**Comment by druv5319** [comment]
Yeah! Feel free to submit a PR. Thanks.

**Comment by erikmaday** [comment]
I also figured out a way to get around the API rate limit.

I only ran into it with the goat scraper. What I determined is if you change the User-Agent in the headers of the request, the requests will go through again.

For example, I switched it to: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0 temporarily.

I may try writing something eventually to auto switch the user-agent if the connection is denied due to a rate limit

**Comment by druv5319** [comment]
Thanks! Yeah i've also had the same issue. The sneaks app [website](https://sneaks-app.com/#/) hasnt been able to connect to Goat or FlightClub probably because of the rate limit on the user agent. I still haven't been able to find a workaround to this. Maybe a proxy might help, but I am unsure.
