### ISSUE TITLE
Integration problem with React App

### ISSUE THREAD

**Issue by jain-aayush1123** [druv5319/Sneaks-API#23]
I have tried to integerate the api in React app and adding the simple line `const SneaksAPI = require("sneaks-api");` gives the error `Cannot read property 'prototype' of undefined`

How to get rid of this or there are some other steps I need to follow?

**Comment by phoenixbeats01** [comment]
`const SneaksAPI = require("sneaks-api");` is the import for nodejs, not React. You need to install nodejs and make an api call from React to your node server.
