### ISSUE TITLE
Error message when running: 

### ISSUE THREAD

**Issue by thiccsupreme** [druv5319/Sneaks-API#5]
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:93835) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Sneaks app listening on port  3000
(node:93835) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  name: 'MongoNetworkError'
}]

**Comment by druv5319** [comment]
You have to install and start mongodb

**Comment by druv5319** [comment]
https://docs.mongodb.com/manual/administration/install-community/  Let me know if this works
