### ISSUE TITLE
Only shoes or all products on StockX?

### ISSUE THREAD

**Issue by MarqueeGaming** [druv5319/Sneaks-API#6]
Was wondering if this api can be used for all products on StockX?

**Comment by druv5319** [comment]
It is restricted only to sneakers. However, you can simply fix this by forking the API and deleting the if statement on line 29 of the stockXScrapper file.

**Comment by MarqueeGaming** [comment]
Awesome I would like to PM you about some business add me on discord.

Coins Wild#8215
