### ISSUE TITLE
Item Descriptions

### ISSUE THREAD

**Issue by MarqueeGaming** [druv5319/Sneaks-API#8]
I did like you said and remove line #29 from StockX scraper file but once I do that I lose the Descriptions from all items. Is there a work around for this?

Discord:
Coins Wild#8215

**Comment by druv5319** [comment]
Do you lose descriptions from shoes? or just clothing items? or all items?

**Comment by MarqueeGaming** [comment]
I still am able to scrape the shoes but all other items on StockX get some random prices from Goat and every other site with no item description.

**Comment by MarqueeGaming** [comment]
@druv5319 Is there any fix for this?

**Comment by druv5319** [comment]
The descriptions are all grabbed from Flight Club and they don't have any clothing items. At the moment this API fully supports only sneakers.

**Comment by MarqueeGaming** [comment]
Is there a way for me to only use StockX and none of the other scrapers?

That way I get all information from StockX all I would need to fetch is:

Sneaker Name
Colorway
Description
Release Date
Retail Price
Style ID
Image Links
Product links
and Price Map.
