### ISSUE TITLE
ImageLinks

### ISSUE THREAD

**Issue by jericoxnavarro** [druv5319/Sneaks-API#9]
The imageLinks is always empty? how can I fix that ?

**Comment by druv5319** [comment]
Looks like Goat has changed their backend API which is where the image links are from. I will try to push out an update to fix this.

**Comment by jericoxnavarro** [comment]
Thank you so much sir I really appreciate it. Btw I'm a student and I'm
using your API to create a website about sneakers for my final project.

**Comment by druv5319** [comment]
Thanks, means a lot!

**Comment by jericoxnavarro** [comment]
Yes the thumbnail only but the imageLink is always empty

**Comment by jericoxnavarro** [comment]
Is the imageLink now working? I saw the demo page https://sneaks-app.com/ and the pic is already working there?

**Comment by druv5319** [comment]
I believe so? It seems that Goat may have changed their backend API to what it was. Let me know if it still works for you.

**Comment by druv5319** [comment]
Should be fixed now. Let me know if it works.
